---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: ingress-nginx
spec:
  selector:
    app: FrontPFE
  type: ClusterIP
  ports:
    - port: 4200
      targetPort: 4200
      protocol: TCP
